name: geminis_open_ia
description: "A Flutter project to test Geminis And Open IA"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dart_openai: ^5.1.0
  google_generative_ai: ^0.4.0
  flutter_document_scanner: ^1.1.1
  flutter_dotenv: ^5.1.0
  mime: ^1.0.5
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env